sudo: required
branches:
  only:
    - master
language: ruby
cache: bundler
dist: trusty
services:
- docker
bundler_args: "--without integration tools maintenance deploy"
before_install:
- gem update --system
- gem update bundler
- gem --version
matrix:
  include:
  - rvm: 2.1.10
  - rvm: 2.2.6
  - rvm: 2.3.3
    script: bundle exec rake $SUITE
    env: SUITE="lint test test:functional"
  - rvm: 2.3.3
    script: bundle exec rake $SUITE
    env: SUITE="test:resources config=test/test.yaml" N=2
  - rvm: 2.3.3
    script: bundle exec rake $SUITE
    env: SUITE="test:resources config=test/test-extra.yaml" N=2
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS=default-ubuntu-1204 DOCKER=true
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-ubuntu-1604' DOCKER=true
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-centos-68' DOCKER=true
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-centos-7' DOCKER=true
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-debian-8' DOCKER=true
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-oracle-72' DOCKER=true
  - rvm: 2.3.3
    bundler_args: "--without guard tools"
    script: bundle exec rake $SUITE
    env: SUITE=test:integration OS='default-fedora-24' DOCKER=true
  allow_failures:
  - env: SUITE="test:resources config=test/test.yaml" N=2
  - env: SUITE="test:resources config=test/test-extra.yaml" N=2
  - rvm: 2.4.1
    sudo: false
    cache:
      apt: true
      bundle: true
    addons:
      apt:
        packages:
        - curl
        - nodejs
    env:
      - AFFECTED_DIRS="www"
      - secure: "jdzXUhP1o7RkfSikZLKgUcCIaKqLjqWa35dnxWnz7qAQ2draRKa7I7cXmUv76BZkW8HBUUH11dOi8YOVxPYPOzaqvcTCfqNqGVxsT9epgWa7rA8aXMXkECp548ry1rYJQpti9zpwsoe2GQyNPr9vNiWMiyj51CaABmZ6JzmFEEqlZc8vqpqWeqJvIqaibQGk7ByLKmi4R44fVwFKIG39RuxV+alc/G4nnQ2zmNTFuy8uFGs5EghQvRytzWY+s2AKtDiZ0YXYOII1Nl1unXNnNoQt9oI209ztlSm1+XOuTPelW6bEIx5i7OZFaSRPgJzWnkGN85C9nBE08L2az9Jz18/rYJF4fdVRttdGskueyYI21lh1FwlAg51ZG0RfLTYk2Pq+k4c+NO1cfmGcaXBwihfD5BWqrILU5HHkYszXCSmgl4hscC7/BS4Kgcq2z32JJwV8B+x4XngM0G4uzIn1Soia3lZXEKdnfVsxFDdMQ7FK60F3uQlq/44LRkZujRhqfAKOiz+0tsLexWzj7wK+DJY9Y00CUfh7xcxRxDxFNpOv1FWYFB9lUlaOt3HDHgUoksqbURiUzhOZZzTE/1MAtF2K6mbpME5CbN08J88L5JBlb+CX79XCzj30lNMeS0I/dCRQEmkygr2eJYxvRO2qsBNuphs4SWk8NZyS/llVZFI="
    before_install: ./support/ci/fast_pass.sh || exit 0
    script: ./support/ci/deploy_website_to_acceptance.sh

deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: uI2Zy3z4ljvOoG/6E4XPmSDg4QX5jmUfp6N9lzOfOosuZGjiGG6cWe4QMfidIz4/B5Ctp9X78bYCPxLkhCPmY9qcsR6eimQsC5AwGJhQF2Fz5fSX12LO+P4H7bis/A7cP+6QYNU8n9oXy6MYIdaw8aLJoEK4tKlNueWYhKG99O1taiF6qXsKkuNXZW7LT3B774IRCK0+BUknfW22ksAOeSpk10dkPXW5lEluXq/Q60L6+Cy01Yix1gLNav7ftMeOtE968mK3L1mzf0L3q8Tih3PLwEzYZRYQRTsd8f1J6XmNZtpdW5QiehvX08ZiFT28Dx15GMp5OKc7TnfU5avm8ryxFJB8xfdrkwNPf/UB3z1IVpHIJ6ZQlHDaiJBL429ZgYSCwrdk71IHWaAK4zSuOZyE+y9EmXbdgLLMgY6QIVrgoBLzzHLCQADXchrMaYR8LIkKI5euOfl3d96sSqXrIN/v1LSlPG/Z1LVO07cYarVGy3J/iM5aTghw3ixZcdlepGrU9DIxe7kRhmz7OLDGTZiPyRzXX1IRjaxSBMGmQSJVv6+r2UJRLmpC3W+1ysXY7nZtffzrFXHGacyvcIHxm8KSPvHgfloPvgFeebcTHcly50TOcZuBc4ZF9HZwWR5lEg/1OX5puBYE7IYfLyFm48+pqFk++tbn2glE742BhkY=
